name: vessel_boost
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - pytorch=2.5.0
  - torchvision=0.20.0
  - torchaudio=2.5.0
  - pytorch-cuda=12.4
  - python=3.10
  - pip
  - jupyter          
  - notebook         
  - jupyterlab       
  - ipython          
  - ipykernel        
  - ipywidgets  
  - pip:
    - numpy==1.26.4
    - scipy==1.15.2
    - torchio==0.20.19
    - scikit-learn==1.1.1
    - pyYAML==6.0.2  
    - matplotlib==3.8.4
    - nibabel==5.2.1
    - patchify==0.2.3
    - tqdm==4.64.1
    - antspyx==0.4.2
    - connected-components-3d==3.13.0
    - osfclient==0.0.5
    - jupyterlmod==5.3.0
    - nnunetv2>=2.6.2  # For nnU-Net model architecture support
