name: vessel_boost_ci

channels:
  - defaults

dependencies:
  - python=3.10
  - pip
  - ipython
  - pip:
      - torch==2.5.0+cpu
      - torchvision==0.20.0+cpu
      - torchaudio==2.5.0+cpu
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - numpy==1.26.4
      - scipy==1.15.2
      - scikit-learn==1.1.1
      - matplotlib==3.8.4
      - pyyaml==6.0.2
      - tqdm==4.64.1
      - nibabel==5.2.1
      - torchio==0.20.19
      - patchify==0.2.3
      - antspyx==0.4.2
      - connected-components-3d==3.13.0
      - osfclient==0.0.5
      - jupyterlmod==5.3.0
      - nnunetv2>=2.6.2